package com.jwt.model;
// Generated Nov 4, 2017 11:05:55 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhotoAlbum generated by hbm2java
 */
@Entity
@Table(name = "photo_album", catalog = "babupateweb")
public class PhotoAlbum implements java.io.Serializable {

	private Integer id;
	private String albumName;
	private String albumImage;
	private Integer totalImg;
	private String status;
	private Date date;
	private Date time;

	public PhotoAlbum() {
	}

	public PhotoAlbum(String albumName, String albumImage, Integer totalImg, String status, Date date, Date time,
			Set photos) {
		this.albumName = albumName;
		this.albumImage = albumImage;
		this.totalImg = totalImg;
		this.status = status;
		this.date = date;
		this.time = time;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "album_name", length = 50)
	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	@Column(name = "album_image", length = 200)
	public String getAlbumImage() {
		return this.albumImage;
	}

	public void setAlbumImage(String albumImage) {
		this.albumImage = albumImage;
	}

	@Column(name = "total_img")
	public Integer getTotalImg() {
		return this.totalImg;
	}

	public void setTotalImg(Integer totalImg) {
		this.totalImg = totalImg;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}



}
