package com.jwt.model;
// Generated Nov 18, 2017 3:01:07 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * T1 generated by hbm2java
 */
@Entity
@Table(name = "t1", catalog = "babupateweb")
public class T1 implements java.io.Serializable {

	private String col1;

	public T1() {
	}

	public T1(String col1) {
		this.col1 = col1;
	}

	@Id

	@Column(name = "col1", length = 20)
	public String getCol1() {
		return this.col1;
	}

	public void setCol1(String col1) {
		this.col1 = col1;
	}

}
